// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAC591SsdwTfGDJZHYdryB6ri9XTTswk',
    appId: '1:617729333010:web:be1dda263e153b18ab05cb',
    messagingSenderId: '617729333010',
    projectId: 'mobile-valida',
    authDomain: 'mobile-valida.firebaseapp.com',
    storageBucket: 'mobile-valida.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LtVPdNk8SQwS7xfgDVxoGaZC-bJztR8',
    appId: '1:617729333010:android:6247ce2fb41d2156ab05cb',
    messagingSenderId: '617729333010',
    projectId: 'mobile-valida',
    storageBucket: 'mobile-valida.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5lraKew6HDb9iGlwiCtzXwI73MEvX40',
    appId: '1:617729333010:ios:e5640db870e8ceb8ab05cb',
    messagingSenderId: '617729333010',
    projectId: 'mobile-valida',
    storageBucket: 'mobile-valida.appspot.com',
    iosBundleId: 'com.example.phoneAuthFirebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5lraKew6HDb9iGlwiCtzXwI73MEvX40',
    appId: '1:617729333010:ios:612a5e0632e078c9ab05cb',
    messagingSenderId: '617729333010',
    projectId: 'mobile-valida',
    storageBucket: 'mobile-valida.appspot.com',
    iosBundleId: 'com.example.phoneAuthFirebaseTutorial.RunnerTests',
  );
}
